/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as AuthUsersImport } from './routes/_auth/users'
import { Route as AuthPlaygroundImport } from './routes/_auth/playground'
import { Route as AuthAdminsImport } from './routes/_auth/admins'
import { Route as AuthAdminsNewImport } from './routes/_auth/admins.new'
import { Route as AuthAdminsAdminIdEditImport } from './routes/_auth/admins.$adminId.edit'
import { Route as AuthAdminsAdminIdDeleteImport } from './routes/_auth/admins.$adminId.delete'
import { Route as AuthAdminsAdminIdChangepwImport } from './routes/_auth/admins.$adminId.changepw'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthUsersRoute = AuthUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any)

const AuthPlaygroundRoute = AuthPlaygroundImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAdminsRoute = AuthAdminsImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAdminsNewRoute = AuthAdminsNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthAdminsRoute,
} as any)

const AuthAdminsAdminIdEditRoute = AuthAdminsAdminIdEditImport.update({
  id: '/$adminId/edit',
  path: '/$adminId/edit',
  getParentRoute: () => AuthAdminsRoute,
} as any)

const AuthAdminsAdminIdDeleteRoute = AuthAdminsAdminIdDeleteImport.update({
  id: '/$adminId/delete',
  path: '/$adminId/delete',
  getParentRoute: () => AuthAdminsRoute,
} as any)

const AuthAdminsAdminIdChangepwRoute = AuthAdminsAdminIdChangepwImport.update({
  id: '/$adminId/changepw',
  path: '/$adminId/changepw',
  getParentRoute: () => AuthAdminsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/admins': {
      id: '/_auth/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AuthAdminsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/playground': {
      id: '/_auth/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AuthPlaygroundImport
      parentRoute: typeof AuthImport
    }
    '/_auth/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersImport
      parentRoute: typeof AuthImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/admins/new': {
      id: '/_auth/admins/new'
      path: '/new'
      fullPath: '/admins/new'
      preLoaderRoute: typeof AuthAdminsNewImport
      parentRoute: typeof AuthAdminsImport
    }
    '/_auth/admins/$adminId/changepw': {
      id: '/_auth/admins/$adminId/changepw'
      path: '/$adminId/changepw'
      fullPath: '/admins/$adminId/changepw'
      preLoaderRoute: typeof AuthAdminsAdminIdChangepwImport
      parentRoute: typeof AuthAdminsImport
    }
    '/_auth/admins/$adminId/delete': {
      id: '/_auth/admins/$adminId/delete'
      path: '/$adminId/delete'
      fullPath: '/admins/$adminId/delete'
      preLoaderRoute: typeof AuthAdminsAdminIdDeleteImport
      parentRoute: typeof AuthAdminsImport
    }
    '/_auth/admins/$adminId/edit': {
      id: '/_auth/admins/$adminId/edit'
      path: '/$adminId/edit'
      fullPath: '/admins/$adminId/edit'
      preLoaderRoute: typeof AuthAdminsAdminIdEditImport
      parentRoute: typeof AuthAdminsImport
    }
  }
}

// Create and export the route tree

interface AuthAdminsRouteChildren {
  AuthAdminsNewRoute: typeof AuthAdminsNewRoute
  AuthAdminsAdminIdChangepwRoute: typeof AuthAdminsAdminIdChangepwRoute
  AuthAdminsAdminIdDeleteRoute: typeof AuthAdminsAdminIdDeleteRoute
  AuthAdminsAdminIdEditRoute: typeof AuthAdminsAdminIdEditRoute
}

const AuthAdminsRouteChildren: AuthAdminsRouteChildren = {
  AuthAdminsNewRoute: AuthAdminsNewRoute,
  AuthAdminsAdminIdChangepwRoute: AuthAdminsAdminIdChangepwRoute,
  AuthAdminsAdminIdDeleteRoute: AuthAdminsAdminIdDeleteRoute,
  AuthAdminsAdminIdEditRoute: AuthAdminsAdminIdEditRoute,
}

const AuthAdminsRouteWithChildren = AuthAdminsRoute._addFileChildren(
  AuthAdminsRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminsRoute: typeof AuthAdminsRouteWithChildren
  AuthPlaygroundRoute: typeof AuthPlaygroundRoute
  AuthUsersRoute: typeof AuthUsersRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminsRoute: AuthAdminsRouteWithChildren,
  AuthPlaygroundRoute: AuthPlaygroundRoute,
  AuthUsersRoute: AuthUsersRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/admins': typeof AuthAdminsRouteWithChildren
  '/playground': typeof AuthPlaygroundRoute
  '/users': typeof AuthUsersRoute
  '/': typeof AuthIndexRoute
  '/admins/new': typeof AuthAdminsNewRoute
  '/admins/$adminId/changepw': typeof AuthAdminsAdminIdChangepwRoute
  '/admins/$adminId/delete': typeof AuthAdminsAdminIdDeleteRoute
  '/admins/$adminId/edit': typeof AuthAdminsAdminIdEditRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admins': typeof AuthAdminsRouteWithChildren
  '/playground': typeof AuthPlaygroundRoute
  '/users': typeof AuthUsersRoute
  '/': typeof AuthIndexRoute
  '/admins/new': typeof AuthAdminsNewRoute
  '/admins/$adminId/changepw': typeof AuthAdminsAdminIdChangepwRoute
  '/admins/$adminId/delete': typeof AuthAdminsAdminIdDeleteRoute
  '/admins/$adminId/edit': typeof AuthAdminsAdminIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/admins': typeof AuthAdminsRouteWithChildren
  '/_auth/playground': typeof AuthPlaygroundRoute
  '/_auth/users': typeof AuthUsersRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/admins/new': typeof AuthAdminsNewRoute
  '/_auth/admins/$adminId/changepw': typeof AuthAdminsAdminIdChangepwRoute
  '/_auth/admins/$adminId/delete': typeof AuthAdminsAdminIdDeleteRoute
  '/_auth/admins/$adminId/edit': typeof AuthAdminsAdminIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/admins'
    | '/playground'
    | '/users'
    | '/'
    | '/admins/new'
    | '/admins/$adminId/changepw'
    | '/admins/$adminId/delete'
    | '/admins/$adminId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admins'
    | '/playground'
    | '/users'
    | '/'
    | '/admins/new'
    | '/admins/$adminId/changepw'
    | '/admins/$adminId/delete'
    | '/admins/$adminId/edit'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/admins'
    | '/_auth/playground'
    | '/_auth/users'
    | '/_auth/'
    | '/_auth/admins/new'
    | '/_auth/admins/$adminId/changepw'
    | '/_auth/admins/$adminId/delete'
    | '/_auth/admins/$adminId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/admins",
        "/_auth/playground",
        "/_auth/users",
        "/_auth/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/admins": {
      "filePath": "_auth/admins.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/admins/new",
        "/_auth/admins/$adminId/changepw",
        "/_auth/admins/$adminId/delete",
        "/_auth/admins/$adminId/edit"
      ]
    },
    "/_auth/playground": {
      "filePath": "_auth/playground.tsx",
      "parent": "/_auth"
    },
    "/_auth/users": {
      "filePath": "_auth/users.tsx",
      "parent": "/_auth"
    },
    "/_auth/": {
      "filePath": "_auth/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/admins/new": {
      "filePath": "_auth/admins.new.tsx",
      "parent": "/_auth/admins"
    },
    "/_auth/admins/$adminId/changepw": {
      "filePath": "_auth/admins.$adminId.changepw.tsx",
      "parent": "/_auth/admins"
    },
    "/_auth/admins/$adminId/delete": {
      "filePath": "_auth/admins.$adminId.delete.tsx",
      "parent": "/_auth/admins"
    },
    "/_auth/admins/$adminId/edit": {
      "filePath": "_auth/admins.$adminId.edit.tsx",
      "parent": "/_auth/admins"
    }
  }
}
ROUTE_MANIFEST_END */
