/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthUsersRouteImport } from './routes/_auth/users'
import { Route as AuthPlaygroundRouteImport } from './routes/_auth/playground'
import { Route as AuthAdminsRouteImport } from './routes/_auth/admins'
import { Route as AuthUsersNewRouteImport } from './routes/_auth/users.new'
import { Route as AuthAdminsNewRouteImport } from './routes/_auth/admins.new'
import { Route as AuthUsersUserIdDeleteRouteImport } from './routes/_auth/users.$userId.delete'
import { Route as AuthAdminsAdminIdEditRouteImport } from './routes/_auth/admins.$adminId.edit'
import { Route as AuthAdminsAdminIdDeleteRouteImport } from './routes/_auth/admins.$adminId.delete'
import { Route as AuthAdminsAdminIdChangepwRouteImport } from './routes/_auth/admins.$adminId.changepw'
import { Route as AuthUsersUserIdKeysNewRouteImport } from './routes/_auth/users.$userId.keys.new'
import { Route as AuthUsersUserIdKeysKeyIdRevokeRouteImport } from './routes/_auth/users.$userId.keys.$keyId.revoke'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersRoute = AuthUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPlaygroundRoute = AuthPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminsRoute = AuthAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersNewRoute = AuthUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthUsersRoute,
} as any)
const AuthAdminsNewRoute = AuthAdminsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthAdminsRoute,
} as any)
const AuthUsersUserIdDeleteRoute = AuthUsersUserIdDeleteRouteImport.update({
  id: '/$userId/delete',
  path: '/$userId/delete',
  getParentRoute: () => AuthUsersRoute,
} as any)
const AuthAdminsAdminIdEditRoute = AuthAdminsAdminIdEditRouteImport.update({
  id: '/$adminId/edit',
  path: '/$adminId/edit',
  getParentRoute: () => AuthAdminsRoute,
} as any)
const AuthAdminsAdminIdDeleteRoute = AuthAdminsAdminIdDeleteRouteImport.update({
  id: '/$adminId/delete',
  path: '/$adminId/delete',
  getParentRoute: () => AuthAdminsRoute,
} as any)
const AuthAdminsAdminIdChangepwRoute =
  AuthAdminsAdminIdChangepwRouteImport.update({
    id: '/$adminId/changepw',
    path: '/$adminId/changepw',
    getParentRoute: () => AuthAdminsRoute,
  } as any)
const AuthUsersUserIdKeysNewRoute = AuthUsersUserIdKeysNewRouteImport.update({
  id: '/$userId/keys/new',
  path: '/$userId/keys/new',
  getParentRoute: () => AuthUsersRoute,
} as any)
const AuthUsersUserIdKeysKeyIdRevokeRoute =
  AuthUsersUserIdKeysKeyIdRevokeRouteImport.update({
    id: '/$userId/keys/$keyId/revoke',
    path: '/$userId/keys/$keyId/revoke',
    getParentRoute: () => AuthUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/admins': typeof AuthAdminsRouteWithChildren
  '/playground': typeof AuthPlaygroundRoute
  '/users': typeof AuthUsersRouteWithChildren
  '/admins/new': typeof AuthAdminsNewRoute
  '/users/new': typeof AuthUsersNewRoute
  '/admins/$adminId/changepw': typeof AuthAdminsAdminIdChangepwRoute
  '/admins/$adminId/delete': typeof AuthAdminsAdminIdDeleteRoute
  '/admins/$adminId/edit': typeof AuthAdminsAdminIdEditRoute
  '/users/$userId/delete': typeof AuthUsersUserIdDeleteRoute
  '/users/$userId/keys/new': typeof AuthUsersUserIdKeysNewRoute
  '/users/$userId/keys/$keyId/revoke': typeof AuthUsersUserIdKeysKeyIdRevokeRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admins': typeof AuthAdminsRouteWithChildren
  '/playground': typeof AuthPlaygroundRoute
  '/users': typeof AuthUsersRouteWithChildren
  '/': typeof AuthIndexRoute
  '/admins/new': typeof AuthAdminsNewRoute
  '/users/new': typeof AuthUsersNewRoute
  '/admins/$adminId/changepw': typeof AuthAdminsAdminIdChangepwRoute
  '/admins/$adminId/delete': typeof AuthAdminsAdminIdDeleteRoute
  '/admins/$adminId/edit': typeof AuthAdminsAdminIdEditRoute
  '/users/$userId/delete': typeof AuthUsersUserIdDeleteRoute
  '/users/$userId/keys/new': typeof AuthUsersUserIdKeysNewRoute
  '/users/$userId/keys/$keyId/revoke': typeof AuthUsersUserIdKeysKeyIdRevokeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/admins': typeof AuthAdminsRouteWithChildren
  '/_auth/playground': typeof AuthPlaygroundRoute
  '/_auth/users': typeof AuthUsersRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/_auth/admins/new': typeof AuthAdminsNewRoute
  '/_auth/users/new': typeof AuthUsersNewRoute
  '/_auth/admins/$adminId/changepw': typeof AuthAdminsAdminIdChangepwRoute
  '/_auth/admins/$adminId/delete': typeof AuthAdminsAdminIdDeleteRoute
  '/_auth/admins/$adminId/edit': typeof AuthAdminsAdminIdEditRoute
  '/_auth/users/$userId/delete': typeof AuthUsersUserIdDeleteRoute
  '/_auth/users/$userId/keys/new': typeof AuthUsersUserIdKeysNewRoute
  '/_auth/users/$userId/keys/$keyId/revoke': typeof AuthUsersUserIdKeysKeyIdRevokeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admins'
    | '/playground'
    | '/users'
    | '/admins/new'
    | '/users/new'
    | '/admins/$adminId/changepw'
    | '/admins/$adminId/delete'
    | '/admins/$adminId/edit'
    | '/users/$userId/delete'
    | '/users/$userId/keys/new'
    | '/users/$userId/keys/$keyId/revoke'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admins'
    | '/playground'
    | '/users'
    | '/'
    | '/admins/new'
    | '/users/new'
    | '/admins/$adminId/changepw'
    | '/admins/$adminId/delete'
    | '/admins/$adminId/edit'
    | '/users/$userId/delete'
    | '/users/$userId/keys/new'
    | '/users/$userId/keys/$keyId/revoke'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/admins'
    | '/_auth/playground'
    | '/_auth/users'
    | '/_auth/'
    | '/_auth/admins/new'
    | '/_auth/users/new'
    | '/_auth/admins/$adminId/changepw'
    | '/_auth/admins/$adminId/delete'
    | '/_auth/admins/$adminId/edit'
    | '/_auth/users/$userId/delete'
    | '/_auth/users/$userId/keys/new'
    | '/_auth/users/$userId/keys/$keyId/revoke'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/playground': {
      id: '/_auth/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AuthPlaygroundRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admins': {
      id: '/_auth/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AuthAdminsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/new': {
      id: '/_auth/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AuthUsersNewRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/admins/new': {
      id: '/_auth/admins/new'
      path: '/new'
      fullPath: '/admins/new'
      preLoaderRoute: typeof AuthAdminsNewRouteImport
      parentRoute: typeof AuthAdminsRoute
    }
    '/_auth/users/$userId/delete': {
      id: '/_auth/users/$userId/delete'
      path: '/$userId/delete'
      fullPath: '/users/$userId/delete'
      preLoaderRoute: typeof AuthUsersUserIdDeleteRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/admins/$adminId/edit': {
      id: '/_auth/admins/$adminId/edit'
      path: '/$adminId/edit'
      fullPath: '/admins/$adminId/edit'
      preLoaderRoute: typeof AuthAdminsAdminIdEditRouteImport
      parentRoute: typeof AuthAdminsRoute
    }
    '/_auth/admins/$adminId/delete': {
      id: '/_auth/admins/$adminId/delete'
      path: '/$adminId/delete'
      fullPath: '/admins/$adminId/delete'
      preLoaderRoute: typeof AuthAdminsAdminIdDeleteRouteImport
      parentRoute: typeof AuthAdminsRoute
    }
    '/_auth/admins/$adminId/changepw': {
      id: '/_auth/admins/$adminId/changepw'
      path: '/$adminId/changepw'
      fullPath: '/admins/$adminId/changepw'
      preLoaderRoute: typeof AuthAdminsAdminIdChangepwRouteImport
      parentRoute: typeof AuthAdminsRoute
    }
    '/_auth/users/$userId/keys/new': {
      id: '/_auth/users/$userId/keys/new'
      path: '/$userId/keys/new'
      fullPath: '/users/$userId/keys/new'
      preLoaderRoute: typeof AuthUsersUserIdKeysNewRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/users/$userId/keys/$keyId/revoke': {
      id: '/_auth/users/$userId/keys/$keyId/revoke'
      path: '/$userId/keys/$keyId/revoke'
      fullPath: '/users/$userId/keys/$keyId/revoke'
      preLoaderRoute: typeof AuthUsersUserIdKeysKeyIdRevokeRouteImport
      parentRoute: typeof AuthUsersRoute
    }
  }
}

interface AuthAdminsRouteChildren {
  AuthAdminsNewRoute: typeof AuthAdminsNewRoute
  AuthAdminsAdminIdChangepwRoute: typeof AuthAdminsAdminIdChangepwRoute
  AuthAdminsAdminIdDeleteRoute: typeof AuthAdminsAdminIdDeleteRoute
  AuthAdminsAdminIdEditRoute: typeof AuthAdminsAdminIdEditRoute
}

const AuthAdminsRouteChildren: AuthAdminsRouteChildren = {
  AuthAdminsNewRoute: AuthAdminsNewRoute,
  AuthAdminsAdminIdChangepwRoute: AuthAdminsAdminIdChangepwRoute,
  AuthAdminsAdminIdDeleteRoute: AuthAdminsAdminIdDeleteRoute,
  AuthAdminsAdminIdEditRoute: AuthAdminsAdminIdEditRoute,
}

const AuthAdminsRouteWithChildren = AuthAdminsRoute._addFileChildren(
  AuthAdminsRouteChildren,
)

interface AuthUsersRouteChildren {
  AuthUsersNewRoute: typeof AuthUsersNewRoute
  AuthUsersUserIdDeleteRoute: typeof AuthUsersUserIdDeleteRoute
  AuthUsersUserIdKeysNewRoute: typeof AuthUsersUserIdKeysNewRoute
  AuthUsersUserIdKeysKeyIdRevokeRoute: typeof AuthUsersUserIdKeysKeyIdRevokeRoute
}

const AuthUsersRouteChildren: AuthUsersRouteChildren = {
  AuthUsersNewRoute: AuthUsersNewRoute,
  AuthUsersUserIdDeleteRoute: AuthUsersUserIdDeleteRoute,
  AuthUsersUserIdKeysNewRoute: AuthUsersUserIdKeysNewRoute,
  AuthUsersUserIdKeysKeyIdRevokeRoute: AuthUsersUserIdKeysKeyIdRevokeRoute,
}

const AuthUsersRouteWithChildren = AuthUsersRoute._addFileChildren(
  AuthUsersRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminsRoute: typeof AuthAdminsRouteWithChildren
  AuthPlaygroundRoute: typeof AuthPlaygroundRoute
  AuthUsersRoute: typeof AuthUsersRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminsRoute: AuthAdminsRouteWithChildren,
  AuthPlaygroundRoute: AuthPlaygroundRoute,
  AuthUsersRoute: AuthUsersRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
