/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_LLMSVC_API_ROOT: string
  readonly VITE_LLMSVC_STAGE: string
  readonly VITE_LLMSVC_DEV_MODE: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}