# Do a production deploy on every release publish

name: Deploy Production

on:
  release:
    types: [published]

jobs:
  Deploy:
    runs-on: ubuntu-24.04-arm
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE }}
      - name: Install backend dependencies
        run: npm install
      - name: Install frontend dependencies
        run: cd ui && npm install --force
      - name: Install SST providers
        run: npx sst install
      - name: Deploy
        run: npx sst deploy --stage production
      - name: Seed default admin
        env:
          DEFAULT_ADMIN_EMAIL: ${{ secrets.DEFAULT_ADMIN_EMAIL }}
          DEFAULT_ADMIN_PW: ${{ secrets.DEFAULT_ADMIN_PW }}
        run: npm run seed:admin "Default Admin" "$DEFAULT_ADMIN_EMAIL" "$DEFAULT_ADMIN_PW"
